name: TOC Generator

description: GitHub Action to generate TOC.

author: Trang Le

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token used to make API requests or git authentication.
    default: ${{ github.token }}
    required: true
  API_TOKEN:
    description: Secret GitHub API token used to make API requests.
    required: false

  TARGET_PATHS:
    description: Target file path. (Comma separated, @see https://github.com/thlorenz/doctoc#adding-toc-to-individual-files)
    default: 'README*.md'
    required: true
  STAT_TITLE:
    description: TOC Title
    default: '**Latest first-time contributor stats**'
    required: false
  COMMIT_MESSAGE:
    description: Commit message.
    required: true
    default: 'chore(docs): update TOC'
  COMMIT_NAME:
    description: Git commit name.
    default: ''
    required: false
  COMMIT_EMAIL:
    description: Git commit email.
    default: ''
    required: false

branding:
  icon: 'book-open'
  color: 'blue'

runs:
  using: node12
  main: index.js
