name: Pull request merged

on:
  pull_request:
    types: [closed]

jobs:
  first_time_contributor:
    name: Update first-time contributor stats if necessary
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJSON(github.event) }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Get author's past PRs
        run: |
          echo "$EVENT"
      - uses: actions/checkout@v2
      - name: Insert first-time contributor stats
        uses: ./
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #   if: env.PR_COUNT > 1