on:
  push:
    branches:
      - main

name: Pull request merged

jobs:
  build:
    name: Check if it's a merged PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Get Github env
        run: |
          echo $GITHUB_ENV